volumes:
  pothole_db: {}

services:
  db:
    image: postgres:16-alpine
    container_name: pothole_postgres
    env_file: 
      - ./.env
    volumes:
      - pothole_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  pgadmin:
    image: elestio/pgadmin:REL-8_13
    container_name: pothole_pgAdmin
    env_file: 
      - ./.env
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/storage:/var/lib/pgadmin/storage


